### PR TITLE
Add simple implementation of getLocations on iOS

### PR DESCRIPTION
**Pull request by anta-semenov**

### CODE REVIEW

**Comment by mauron85** [comment]
This was implemented in https://github.com/mauron85/react-native-background-geolocation/blob/next/ios/RCTBackgroundGeolocation/RCTBackgroundGeolocation.m#L126

However not pushed to master yet.

**Comment by anta-semenov** [comment]
Are there any chances that it will be pushed to master in near future? Because it's very needed feature for our project.

**Comment by neo125874** [comment]
+1 because of reading the readme  describe that it works at ios, but seems not working like this lib's example?

**Comment by neo125874** [comment]
@anta-semenov hello, did you use this PR's method? could it works?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 165 days. You may reopen this issue if it has been closed in error.

**Pull request closed without merging**
