### PR TITLE
Add prepublish script to package.json

### PR DESCRIPTION
**Pull request by dobrynia**
At the moment, before the publication of the package, the script does not work, since it was not added to the **package.json** file. As a consequence, there is no copying of files from the submodules and an error of missing files appears during the build of the application.
Another topic for discussion is adding a **prepublishOnly** script to the **package.json** file. The 
[documentation](https://docs.npmjs.com/misc/scripts) says it differs from the **prepublish** in that it works only before the publication of the npm package. **prepublish** script is triggered also **npm install** is launched. I guess that your goal is the first option, **prepublishOnly**. It's right?

### CODE REVIEW

**Comment by mauron85** [comment]
@dobrynia thank you for raising this. I'm perfectly aware of this "issue".

I didn't add `prepublish.sh` into prepublishOnly for following reasons:
1. as bash script will only work on unixes. We probably need prepublish script written in javascript, that will run in nodejs.
2. should prepublish script pull git submodule updates automatically? If not how can be prepublish script sure that submodule is in correct branch, pointing to correct head ...?

Mainly because of 2. step I consider automatic prepublish step as very dangerous and prefer running it manually.

**Comment by dobrynia** [comment]
@mauron85 
1. I wrote a cross-platform script. I supplemented the script with one line, with which the latest submodules changes are pulled. For those who install the module from the repository, all changes will be received during **npm install** as well, because I returned the name of the script to _prepublish_ .
2. When you enter **npm publish** command, this script is triggered. I think we can keep a stable version of submodules in a separate branch, perhaps in **master**, and work in another branch (for example, **develop**).

**Comment by mauron85** [comment]
Nice. I like that. 

Regarding point 2:

I suggest let's keep only: `git submodule init && git submodule update` in both `script.js` and `scripts.bat`.

From my experience it will set submodule repo HEAD exactly to commit hash as defined in `.git/modules/common/refs/heads/master` - this is also the value you will find when you click on `common` folder here on github and should not be updated itself (eg. by command `git submodule foreach git pull`). 

Keep in mind that `common` submodule is shared between cordova and RN and you don't want automatically use latest commit from `master`. It may contain incompatible changes.

It only cause very little "inconvenience" for maintainer and actually only adds two more steps to the workflow:

1. set common submodule head to manually to compatible commit hash. It could latest master, but don't it could be also something else (eg... other branch, other commit, tag...)
2. commit changes from step 1.
3. now you can run `npm publish`

**Comment by mauron85** [comment]
In other words if you remove `git submodule foreach git pull` from both `script.sh` and `script.bat` I think I can safely merge this.

**Comment by dobrynia** [comment]
I understood the course of your thoughts. Give me a couple of minutes.

**Comment by mauron85** [comment]
Also thinking about chaining commands so if any fails, the script will not continue (could be dangerous):

`script.sh`
```
# mkdir can fail
mkdir -p android/lib/src/main/res/

git submodule init && git submodule update && cp -r android/common/src/main/java/* android/lib/src/main/java/
```

So if any of commands fail, script will return non zero return code and npm publish should not publish anything in that case (hopefully).

**Comment by mauron85** [comment]
I know I you've aready removed `git submodule foreach git pull`. However I give you one more reason (or maybe I'm giving it rather to myself :).

Having `git submodule foreach git pull`would be dangerous for local installations too. It would pull changes from master and it will brought nasty surprises, like why it's not working. it was working a week ago. This kind of situation would almost impossible to reproduce, because link between RN module and common module would unstable.

**Comment by dobrynia** [comment]
It's done.

**Comment by mauron85** [comment]
Squashed and merged! Thank you for your contribution.

**Comment by kristfal** [comment]
@mauron85 FIY: This fix never made it into master. Due to lack of prepublish scripts for the common lib, installing from master doesn't work any longer.

**Comment by mauron85** [comment]
@kristfal Actually it has been merged but also in turn replaced by better solution that doesn't requires copying of files. react-native link now takes care about registering common subproject. However if you installed plugin before this change you probably need to add subproject manully as stated in [updated instructions](https://github.com/mauron85/react-native-background-geolocation#android-setup). 

>include ':react-native-mauron85-background-geolocation-common'
project(':react-native-mauron85-background-geolocation-common').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-mauron85-background-geolocation/android/common')

You can also try to rerun react-native link, but not sure if it's gonna work.

**Pull request closed without merging**
