### PR TITLE
[iOS] Fix Header Search Paths

### PR DESCRIPTION
**Pull request by Arnaud-J**
This adds an extra layer of hierarchy to the iOS Header Search Paths as suggested by #390

### CODE REVIEW

**Comment by mysport12** [comment]
Looks good to me!

**Comment by minikin** [comment]
any news?

**Comment by stevenleeg** [comment]
I just tried incorporating background-geolocation into my app using this branch but, upon compilation, am seeing this error:

```RCTBackgroundGeolocation/RCTBackgroundGeolocation.h:15:9: fatal error: 'MAURProviderDelegate.h' file not found
#import "MAURProviderDelegate.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.```

@Arnaud-J any idea as to why this issue might be popping up?

**Comment by minikin** [comment]
@stevenleeg  react-native-background-geolocation has a [background-geolocation-ios](https://github.com/mauron85/background-geolocation-ios/search?utf8=%E2%9C%93&q=MAURProviderDelegate&type=) as dependency. Which is integrated with [gitmodules](https://github.com/mauron85/react-native-background-geolocation/blob/master/.gitmodules). That's might be a source of your problem.

**Comment by stevenleeg** [comment]
Hmm, looks like you're right, but I've still been struggling to get it working. I've checked out Arnaud's repository in a separate directory, run `git submodule init` and `git submodule update`, then `yarn link` in the module's repo and `yarn link @mauron85/react-native-background-geolocation` in my project, but am still seeing this error:

imagen

**Comment by Arnaud-J** [comment]
@stevenleeg I did not try to install from my repo and I am not an experienced iOS developer so I think I won't have the time to try it at all. Sorry I can't be of more help.

What I did to validate @mysport12 suggestion is use @mauron85/react-native-background-geolocation@0.5.3 and directly modify its `ios/RCTBackgroundGeolocation.xcodeproj/project.pbxproj` file. I then reported the changes in this merge request.

**Comment by minikin** [comment]
@stevenleeg @mysport12 
Anyway, I think that this issue should be addressed. 
Unfortunately, I can't find any guidelines about how to develop and build this project properly.

**Comment by mauron85** [comment]
Guys, what is the status of this. Does this PR works for you and could be merged? Feedback welcome.

**Comment by mysport12** [comment]
It works for me

**Comment by minikin** [comment]
@mauron85 it doesn't work for me. temporarily fixed with post-install patch script.

**Comment by mauron85** [comment]
ok, and where is that patch? Can we merge that instead?

**Comment by RbertKo** [comment]
It work for me too

**Comment by mikebouwmans** [comment]
This actually fixed this issue for me aswell. Together with #414

**Comment by Vednus** [comment]
@stevenleeg did you ever fix this issue. I'm getting your `MAURProviderDelegate.h` file not found error. Also tried this branch with the same results: https://github.com/mauron85/react-native-background-geolocation/pull/416

**Comment by Vednus** [comment]
Actually this works if I manually add it to my podfile via `pod '@mauron85_react-native-background-geolocation', :git => 'git@github.com:hugosbg/react-native-background-geolocation.git', :branch => 'PR', :submodules => true ` because, the pr is referencing the main branch in the podspec and not the branch to be merged in

**Comment by Vednus** [comment]
Got it working but had to manually copy over the git submodule into the `node_modules/@mauron85/react-native-background-geolocation/ios/common` folder after installing. Not sure why the git submodule isn't working...

**Comment by mauron85** [comment]
This should be fixed in version 0.6 by another PR.

**Pull request closed without merging**
