### PR TITLE
Fix headers for RN 0.40.0

### PR DESCRIPTION
**Pull request by mitch104**
To fix breaking changes introduced in RN 0.40.0.

### CODE REVIEW

**Comment by justinobney** [comment]
https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.p714l4p8r

**Comment by mauron85** [comment]
@mitch104 can you adjust your PR according to @justinobney post? So we can support also pre 0.40 RN.

**Comment by pxue** [comment]
any progress on this? @mitch104

**Comment by mauron85** [comment]
should be fixed in 0.2.0-alpha.6

**Pull request closed without merging**
