### PR TITLE
fix iOS implementation for isLocationEnabled

### PR DESCRIPTION
**Pull request by koenpunt**
the implementation didn't match the android api, and therefore resulted in an error

image

### CODE REVIEW

**Comment by wbattel4607** [comment]
We have to use your fork because this one doesn't build for us. We're hoping this PR is merged! :)

**Comment by gianpieroc** [comment]
we have to use your fork too expecting this PR is merged 👍

**Comment by panuhorsmalahti** [comment]
I get this error on RN 0.48. Shouldn't this be merged already?

**Comment by mauron85** [comment]
Merged. Thank you for your contribution.

**Pull request merged**
