### PR TITLE
update docs to advice exponent js users

### PR DESCRIPTION
**Pull request by luisguilhermemsalmeida**
I spend some days trying to figure out how to use this lib with Exponent js. I was having compatibility errors and then managed to get it to work on android by changing the gms version.

### CODE REVIEW

**Comment by greyvugrin** [comment]
This info is also relevant when using airbnb's react-native-maps package. Having both installed crashes the app unless you alter the required google package version, as per the example repo:

> Module react-native-maps v0.8.2 requires Google Play Services library version 9.4.0, we need to change node_modules/react-native-mauron85-background-geolocation/android/lib/build.gradle
> 
> dependencies {
>     ...
>     compile 'com.google.android.gms:play-services-location:9.4.0'
>     ...
> }

**Comment by mauron85** [comment]
I've some instructions regarding rn-maps in https://github.com/mauron85/react-native-background-geolocation-example.

But agree that is might be valuable instruction also here in plugin repo.

Only one thing. Can you also add mention about react-native-maps (like you said here)? I will merge it then.

**Comment by luisguilhermemsalmeida** [comment]
Done!

**Comment by greyvugrin** [comment]
Since I originally commented here I saw a different approach that may be better.

See info here:
https://github.com/transistorsoft/react-native-background-geolocation/issues/229

Basically if you edit your `app/build.gradle` and force your own version, you can avoid having to update the `build.gradle` of the package, which would be annoying in the future (have to be careful with upgrades, etc)

**Comment by mauron85** [comment]
merged, thank you

**Pull request merged**
