### PR TITLE
Always update location in iOS

### PR DESCRIPTION
**Pull request by priezz**
Always deliver the location updates to the client (iOS)

Edit: This is the fix for #14. The updates will come with the `type` field set to `raw` to be able to filter them on the app side.

### CODE REVIEW

**Comment by Okipa** [comment]
Hi @priezz, is this pull request related to your issue https://github.com/mauron85/react-native-background-geolocation/issues/14 ?
If it does, I am quite interested !
I would like to get all location updates on iOS but they are rare at the moment.
On Android, that works very well.

**Comment by priezz** [comment]
Yes, it is exactly the fix for #14

**Comment by tehmou** [comment]
@priezz I was trying this out, but it would seem that I only get around 10 raw locations and then they stop. Any idea what it might be, and has this been working for you fine?

**Comment by priezz** [comment]
@tehmou, sorry for late reply. For me this change is working perfectly and I collect the locations data constantly for rather long periods of time in this app https://itunes.apple.com/ru/app/bestimulated/id1173123775?mt=8. Have no idea, what is the problem in your case...

**Comment by priezz** [comment]
@mauron85, could you comment this PR? Is it nessesary to improve it or it's description somehow?

**Comment by Okipa** [comment]
I tried your patch priezz, and it does work quite well !
I have new locations triggered in intervals varying between 1 and 15 seconds.
This is a lot more precise for running or bike ride tracking for exemple ;)
I would have a question about this : is the configuration (desiredAccuracy, distanceFilter, ...) used by this change or does it trigger new location event more often but randomly ?
Before using this, I would love to get a bit more informations about what that patch changes.
Thanks by advance for your precisions !

**Comment by mauron85** [comment]
Ok, but keep in mind this patch is bypassing plugin's queue. So if you invoke some long running operation in your javascript, app might be terminated.

**Comment by Okipa** [comment]
Ok, thanks for the warning.
Indeed, I am using this package for bicycle rides, so I shouldn't use this patch.
Too bad, that was interesting on the paper ;)

**Comment by priezz** [comment]
I use this patch in production and the app is not terminated when running
for a few hours (never tried longer). Normally the plugin puts the
collected data into it's own queue and when the app asks, it gives it back.
But for me it does not work well and I have my own processing and storage
at the app side. Marian, please advice if the checks are passed before I
transfer the data to the app or they are done later? All I need is to
collect the data in time, accuracy, delta and friends are checked on the
app side, so I never bothered.

2017-05-29 15:39 GMT+03:00 Arthur LORENT <notifications@github.com>:

**Comment by mauron85** [comment]
@priezz I probably need to to take closer look why the patch is actually necessary, so you don't get all the location updates. Maybe there is problem we queue processing itself.

**Comment by Okipa** [comment]
That would be a great news @mauron85.
I made a test this morning : the geolocation was running during 15 minutes and my app captured 26 GPS coordinates.
That gives an average of 35 seconds for a GPS coordinate capture.  
I don't know if that could make a difference but I was walking for the half way and in the tramway for the other half. I didn't noticed any difference in the time interval between 2 captures.
For a bicycle ride this time interval can be precise enought, but for a run tracking, for example, this not very precise indeed.
FWI, here is my package configuration in case you would be interested (in order to have a full real test report) :  
```
        // ********************************* all (both android and ios)
        desiredAccuracy: 0,
        stationaryRadius: 1,
        distanceFilter: 1,
        debug: false,
        stopOnTerminate: true,
        locationTimeout: 30,
        // ********************************* android
        startOnBoot: false,
        startForeground: true,
        notificationTitle: 'Géolocalisation écovélo en cours',
        notificationText: 'enabled',
        notificationIconColor: Colors.DEFAULT,
        locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
        interval: 10000,
        fastestInterval: 5000,
        activitiesInterval: 10000,
        stopOnStillActivity: false,
        // ********************************* ios
        activityType: 'Fitness',
        saveBatteryOnBackground: false,
```

**Comment by priezz** [comment]
Using my patch I collect the location once per second - use it for walking,
running, riding bike, etc. Here is the config:

desiredAccuracy: 0,
stationaryRadius: 0,
distanceFilter: 0,
debug: false,
startOnBoot: false,
startForeground: true,
stopOnTerminate: false,
locationProvider: BackgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
saveBatteryOnBackground: false,
interval: 1000,
fastestInterval: 1000,
activitiesInterval: 100,
stopOnStillActivity: false,
activityType: 'Fitness',
maxLocations: 0,
syncThreshold: 0,

pauseLocationUpdates: false,
pausesLocationUpdatesAutomatically: false,


2017-05-30 11:47 GMT+03:00 Arthur LORENT <notifications@github.com>:

**Comment by wbattel4607** [comment]
Has there been any further discussion of iOS location update frequency? We use this for our location-based app and while it works great for Android, our iOS users are not having a good time.

**Comment by mauron85** [comment]
Warning: this issue has been inactive for 38 days and will be automatically closed on 2017-12-09 if there is no further activity.

**Pull request closed without merging**
