### PR TITLE
Fixed compile error in React Native 0.48.x

### PR DESCRIPTION
**Pull request by tpisto**

### CODE REVIEW

**Comment by tpisto** [comment]
Tested with iOS 11 and Xcode 9

**Comment by panuhorsmalahti** [comment]
Fixed #108, please merge :)

**Comment by mauron85** [comment]
Don't have time to properly investigate. But I remember fixing headers in commit https://github.com/mauron85/react-native-background-geolocation/commit/9d83368039aed26f88d812247b43c10af3ea0904

This seems to revert that commit. Seems strange, is there react native readme about this change?

**Comment by mauron85** [comment]
Fixed in 0.3.1. Thanks for reporting.

**Pull request merged**
