### PR TITLE
updated type definitions

### PR DESCRIPTION
**Pull request by djereg**
Please let me know if something is wrong, and I will correct it.

### CODE REVIEW

**Comment by mauron85** [comment]
Hi, you should add your name to the definition header. I'll wait and then merge this. Thank you for the contribution.

**Comment by mauron85** [comment]
Merged. Thank you for your contribution!

**Comment by mauron85** [comment]
@djereg there is issue with AccuracyLevel being commented out in cordova variant (but it has same definitions). https://github.com/mauron85/cordova-plugin-background-geolocation/issues/487#issuecomment-436037712

I could uncomment AccuracyLevel, but rather ask you first about the intended behaviour.

**Comment by djereg** [comment]
OMG! Banal mistake.

Solutions:
1. Uncommenting the `AccuracyLevel` type (and setting `desiredAccuracy?: AccuracyLevel`), but it will limit the `desiredAccuracy` value to `0` `100` `1000` `10000`.
2. Uncommenting, and changing to `type AccuracyLevel = number`.  This will allow any numeric values, and will keep the symbolic `AccuracyLevel` type, but in fact it is a number.
3. Leave commented and setting the four constant's type to `number`.

I prefer the 1. option. @mauron85 you?

**Comment by mauron85** [comment]
2 is ok with me

**Comment by djereg** [comment]
Did the changes, option 2., but a bit differently, maybe a better one solution.

Kept `AccuracyLevel` as it is, but added ` | number`. It limits values to `0` `100` `1000` `1000` but allows any other numbers, like 56. 😄 BUT, once if you want to change constants to some stricter values like strings or other, the option remains setting desired accuracy to 56 if someone likes 56. For example filtering locations with accuracy less than (or equal) 56, which I am doing now manually. But this is a future idea, and maybe not a good idea.

**Comment by mauron85** [comment]
Fine with me.

**Pull request merged**
