### PR TITLE
Upgraded Android support version to 23.+

### PR DESCRIPTION
**Pull request by GabiAxel**
Fixes mauron85/react-native-background-geolocation#116

### CODE REVIEW

**Comment by MichielDeMey** [comment]
Nice, let's try to get this merged ASAP. 👍

**Comment by mauron85** [comment]
Sorry guys. Any attempt to lock dependencies version will not be merged. Already talked about it in https://github.com/mauron85/cordova-plugin-background-geolocation/pull/313

**Comment by MichielDeMey** [comment]
Makes sense, however what's currently the proper way forward to fix #116?

**Comment by mauron85** [comment]
Seriously I don't know. This is creepy problem of projects such as react-native where many plugins have to coexists and agree somehow on shared dependencies versions.

Maybe there is clean way how to override plugin settings on a project level.

**Comment by mauron85** [comment]
@MichielDeMey but you can still fork project and lock android support lib version. The only downside I see is that you will have to install it from github (instead of npm) and merge upstream changes from time to time. But hopefully we can find better solution.

**Comment by mauron85** [comment]
I kinda like @alexdunne suggested solution: https://github.com/mauron85/react-native-background-geolocation/issues/116#issuecomment-356575145

Didn't tested it myself. But seems I like adequate solution to this problem.

**Comment by MichielDeMey** [comment]
I tried that, but that did not seem to work at first.

Found out that you need to place this in the `build.gradle` of the `app` module.
Had to restart my Android Studio as well to pick up the changes for some reason.

Thanks, this does seem like the proper way forward. Feel free to close this issue.

**Pull request closed without merging**
