### PR TITLE
Fix used android versions

### PR DESCRIPTION
**Pull request by stephanmantel**
To have the client project stable, the it should not always get the latest version of say the android support library. Like now the latest can be an Alpha build and that can conflict with the client apps versions.

### CODE REVIEW

**Comment by ianaz** [comment]
About this being merged?

**Comment by ianaz** [comment]
Anyways; I had to add:

> import android.Manifest;
> import android.support.v4.app.ActivityCompat;

and set 

> private static final int PERMISSION_REQUEST_CODE = 99;

for it to compile

**Comment by kyledmellander** [comment]
This seems to have solved the problem that I was having on my end. Compiling gave an error: 

Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

**Comment by FredyC** [comment]
@kyledmellander How did you use this fork, please? I am running into the same error message as yiz, so I've installed it as usual `yarn add stephanmantel/react-native-background-geolocation`, but build it has failed with the following instead :/ I am rather rookie to Java and this stuff.

```
:react-native-mauron85-background-geolocation:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java:282: error: package Manifest does not exist
            String[] permissions = { Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION };
                                             ^
/Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java:282: error: package Manifest does not exist
            String[] permissions = { Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION };
                                                                                       ^
/Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java:283: error: cannot find symbol
            ActivityCompat.requestPermissions(activity, permissions, PERMISSION_REQUEST_CODE);
                                                                     ^
  symbol:   variable PERMISSION_REQUEST_CODE
  location: class BackgroundGeolocationModule
/Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java:283: error: cannot find symbol
            ActivityCompat.requestPermissions(activity, permissions, PERMISSION_REQUEST_CODE);
            ^
  symbol:   variable ActivityCompat
  location: class BackgroundGeolocationModule
/Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationPackage.java:26: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: /Users/ci/agent/vstsagent/_work/1/s/node_modules/react-native-mauron85-background-geolocation/android/lib/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java uses or overrides a deprecated API.
```

**Comment by FredyC** [comment]
@ianaz I guess that your tweak is the same thing I need. Can you please help where should I add those?

**Comment by FredyC** [comment]
Ok, I have figured it out. Since @stephanmantel seems to lost interesting in this PR, I made my own fork.

**Comment by ianaz** [comment]
Sorry I just saw it now :) good to know you found a solution

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been inactive for 78 days. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Sorry guys. Any attempt to harwire dependencies version will not merge.
I know and understand that it will temporarily solve your problem.
But this is not maintainable solution. It might work for some of you, but others may require different versions.

If you need to specific libraries go fork this project. 

But please do not pollute npm with your version. Keep it on github and install it from github.

**Comment by FredyC** [comment]
@mauron85 The only solution is to have a fork? Is that some general problem of Gradle? I haven't encountered that with any other lib. Why this lib has this issue?

**Comment by mauron85** [comment]
@FredyC normally there is no reason to fork.

Fork might be needed, only if you're using plugins that are setting their own versions of dependencies (support, google play) and those versions might be in conflict.

Locking version to specific version, here may solve your problem. But it's not silver bullet.
What works for you, will not for others.

**Pull request closed without merging**
