### PR TITLE
iOS RN 0.40 compatibilty

### PR DESCRIPTION
**Pull request by lpusok**
The fix for RN 0.40 ios compatibilty does not work. The imports should be in the format  #import "RCTLog.h".

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
👍 using your PR on a side project because I can't use this repo on current version of React Native :(

**Comment by mauron85** [comment]
@Jarred-Sumner have you tried 0.2.0-alpha.6?

**Comment by mauron85** [comment]
Since 0.2.0-alpha.6 I don't think this is is a thing :-) anymore. Or is it?

**Comment by lpusok** [comment]
It is working with 0.2.0-alpha.6. The bug occured earlier with this version, project clean and XCode restart helped IMO. Can be closed.

**Comment by mauron85** [comment]
ok thanks for update. closing

**Pull request closed without merging**
